serverAddr = "0.0.0.0"
serverPort = 7000

# console or real logFile path like ./frpc.log
log.to = "./frpc.log"
# trace, debug, info, warn, error
log.level = "info"
log.maxDays = 3

auth.method = "token"
auth.token = "#234234dsfdsjewr!dsfvo"

[[proxies]]
name = "sunshine_stream_tcp_47984"
type = "tcp"
localIP = "127.0.0.1"
localPort = 47984
# If remotePort is 0, frps will assign a random port for you
remotePort = 47984

[[proxies]]
name = "sunshine_stream_tcp_47989"
type = "tcp"
localIP = "127.0.0.1"
localPort = 47989
# If remotePort is 0, frps will assign a random port for you
remotePort = 47989

[[proxies]]
name = "sunshine_stream_tcp_47990"
type = "tcp"
localIP = "127.0.0.1"
localPort = 47990
# If remotePort is 0, frps will assign a random port for you
remotePort = 47990

[[proxies]]
name = "sunshine_stream_tcp_48010"
type = "tcp"
localIP = "127.0.0.1"
localPort = 48010
# If remotePort is 0, frps will assign a random port for you
remotePort = 48010

[[proxies]]
name = "sunshine_stream_udp_47998"
type = "udp"
localIP = "127.0.0.1"
localPort = 47998
# If remotePort is 0, frps will assign a random port for you
remotePort = 47998

[[proxies]]
name = "sunshine_stream_udp_47999"
type = "udp"
localIP = "127.0.0.1"
localPort = 47999
# If remotePort is 0, frps will assign a random port for you
remotePort = 47999

[[proxies]]
name = "sunshine_stream_udp_48000"
type = "udp"
localIP = "127.0.0.1"
localPort = 48000
# If remotePort is 0, frps will assign a random port for you
remotePort = 48000